// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ParkingDbContext))]
    [Migration("20220805125024_Add-General-Seeding")]
    partial class AddGeneralSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("By")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<int>("Shift")
                        .HasColumnType("int");

                    b.Property<int>("Space")
                        .HasColumnType("int");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e02bf96-cefb-489a-b6ec-bbe24ad83bb5"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750123"),
                            From = new DateTime(2022, 8, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 13,
                            To = new DateTime(2022, 8, 13, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("fe96babd-40e5-495c-9833-b3c3bb90375a"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750120"),
                            From = new DateTime(2022, 8, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 12,
                            To = new DateTime(2022, 8, 22, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("f94c4cc6-050b-4033-8f51-7cd3db6c87f7"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750107"),
                            From = new DateTime(2022, 9, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 1,
                            To = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("f18cce82-95f9-4eb2-a906-f6c596e9ca9e"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750134"),
                            From = new DateTime(2022, 8, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 6,
                            To = new DateTime(2022, 8, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("7037f92d-8032-4da5-872c-7b96fb851ab6"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750127"),
                            From = new DateTime(2022, 8, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 19,
                            To = new DateTime(2022, 9, 2, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("433dfacb-5ecc-4d25-88a1-0706ee32fa27"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750119"),
                            From = new DateTime(2022, 8, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 9,
                            To = new DateTime(2022, 8, 15, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("081c27e3-d9cb-451b-b514-8c3f512fb195"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750129"),
                            From = new DateTime(2022, 8, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 8,
                            To = new DateTime(2022, 8, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("7e24e3fe-fd1e-44fc-86e9-7ba82c3e9e7c"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750114"),
                            From = new DateTime(2022, 8, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 10,
                            To = new DateTime(2022, 8, 30, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("b850aa6c-f1b8-4fce-b070-770b3a9ae089"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750101"),
                            From = new DateTime(2022, 8, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 12,
                            To = new DateTime(2022, 8, 23, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("7d00dc53-bc23-407e-8521-e2839e391d2b"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750109"),
                            From = new DateTime(2022, 8, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 16,
                            To = new DateTime(2022, 8, 14, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("641d4b01-0954-4c19-9fa0-c6194ab218e6"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750108"),
                            From = new DateTime(2022, 8, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 3,
                            To = new DateTime(2022, 8, 22, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("a9c56b44-13b5-406e-8671-7dee35b5b022"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750111"),
                            From = new DateTime(2022, 8, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 20,
                            To = new DateTime(2022, 8, 23, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("668c8cbb-252d-45cc-a45d-87751d075782"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750143"),
                            From = new DateTime(2022, 8, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 15,
                            To = new DateTime(2022, 8, 14, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("0624fc3a-0d96-4e2a-86a2-a899a91121b2"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750117"),
                            From = new DateTime(2022, 8, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 15,
                            To = new DateTime(2022, 8, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("52fb5e08-9a0d-413a-83fa-98eb82d9f68d"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750149"),
                            From = new DateTime(2022, 8, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 17,
                            To = new DateTime(2022, 8, 31, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("2cd312b6-fab5-44dc-acdc-712b45c24b02"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750110"),
                            From = new DateTime(2022, 8, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 16,
                            To = new DateTime(2022, 8, 27, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("86939f7a-abd8-48e3-b57d-650a6fcf51ac"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750125"),
                            From = new DateTime(2022, 8, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 6,
                            To = new DateTime(2022, 8, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("62d0d91a-7456-40df-8f5f-16016e764348"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750147"),
                            From = new DateTime(2022, 8, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 1,
                            To = new DateTime(2022, 8, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("8b98dc6b-c4cd-4e58-b97f-d6a6c2cbb4f7"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750105"),
                            From = new DateTime(2022, 8, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 18,
                            To = new DateTime(2022, 8, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("a94f3495-8696-400a-81c3-3c7a1d4c5fb3"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750118"),
                            From = new DateTime(2022, 8, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 9,
                            To = new DateTime(2022, 8, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("5803f4c9-84cd-411e-a052-72c4fde616a1"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750103"),
                            From = new DateTime(2022, 8, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 5,
                            To = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("15ea7fca-ae70-4ba5-b1b1-366ad71750d2"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750140"),
                            From = new DateTime(2022, 8, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 2,
                            To = new DateTime(2022, 8, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("67d908df-f45b-4835-89e7-caeb4659d3a4"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750130"),
                            From = new DateTime(2022, 8, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 7,
                            To = new DateTime(2022, 9, 2, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("f17a04b9-799d-4727-a8b4-e3b93ac5c906"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750112"),
                            From = new DateTime(2022, 8, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 3,
                            To = new DateTime(2022, 8, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("bf7c19da-7bc5-4c91-87b4-ab8a286b0b9f"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750124"),
                            From = new DateTime(2022, 8, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 1,
                            To = new DateTime(2022, 8, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("d066996a-7b69-4c01-837e-17810f310d37"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750116"),
                            From = new DateTime(2022, 8, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 11,
                            To = new DateTime(2022, 8, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("42afde00-0d7b-4a4a-867b-64b63e45fa6b"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750136"),
                            From = new DateTime(2022, 8, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 2,
                            To = new DateTime(2022, 8, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("8cee9c31-fc33-4b1e-b5c8-5867ca342bc9"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750126"),
                            From = new DateTime(2022, 8, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 14,
                            To = new DateTime(2022, 8, 15, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("ba8a454f-6296-4bf8-94dd-77d33beaac0f"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750135"),
                            From = new DateTime(2022, 8, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 4,
                            To = new DateTime(2022, 8, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("76219002-37b4-455a-b1ec-64fc5fc76471"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750133"),
                            From = new DateTime(2022, 8, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 4,
                            To = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("f3e5eebd-8516-47ca-ba5c-9ffa0c112e65"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750102"),
                            From = new DateTime(2022, 8, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 14,
                            To = new DateTime(2022, 8, 30, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("318fc089-aaa9-499f-9cb9-032763e4bfbd"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750132"),
                            From = new DateTime(2022, 8, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 16,
                            To = new DateTime(2022, 8, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("34a491cf-ab2a-4bed-8e29-d4a603ca7678"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750131"),
                            From = new DateTime(2022, 8, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 20,
                            To = new DateTime(2022, 8, 22, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("bc80c451-c41f-4c54-a255-bddb0b5cedc1"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750100"),
                            From = new DateTime(2022, 8, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 13,
                            To = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("5270d631-b791-4fb2-8f46-fd34fef92f25"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750137"),
                            From = new DateTime(2022, 8, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 12,
                            To = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("3340e186-8ea4-4bb9-8844-c049dca78e1b"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750104"),
                            From = new DateTime(2022, 8, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 6,
                            To = new DateTime(2022, 8, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("227030ae-e9d6-4381-a3c6-60fb594f90d4"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750121"),
                            From = new DateTime(2022, 8, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 14,
                            To = new DateTime(2022, 8, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("3539862d-c6c6-4fa5-9201-33f28f3fb95a"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750113"),
                            From = new DateTime(2022, 8, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 19,
                            To = new DateTime(2022, 9, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("fc58c834-859b-4dd7-a634-2137099d4ba5"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750145"),
                            From = new DateTime(2022, 8, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 8,
                            To = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("0bb27d95-9112-400b-a0cb-80bcd4692043"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750138"),
                            From = new DateTime(2022, 8, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 4,
                            To = new DateTime(2022, 8, 10, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("9a1a7e48-6363-4e84-aafd-d03707850a49"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750128"),
                            From = new DateTime(2022, 8, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 8,
                            To = new DateTime(2022, 8, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("b9ffcf1a-2116-41d3-bd96-87cf15b963a9"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750142"),
                            From = new DateTime(2022, 8, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 9,
                            To = new DateTime(2022, 8, 30, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("a00e7a40-ebb2-4b52-8ad4-78b400c3b25b"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750115"),
                            From = new DateTime(2022, 8, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 15,
                            To = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("960198f0-d82e-42db-b1dc-c53f24927cb0"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750106"),
                            From = new DateTime(2022, 8, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 14,
                            To = new DateTime(2022, 8, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("54300f33-068b-4691-9a84-1d30be9ef8c0"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750146"),
                            From = new DateTime(2022, 8, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 2,
                            To = new DateTime(2022, 8, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("09daa148-b3bc-40d4-bdae-ea783b9c97a9"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750122"),
                            From = new DateTime(2022, 8, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 11,
                            To = new DateTime(2022, 8, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("40ba4eda-a227-49a8-a2a7-ce79b56252b9"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750144"),
                            From = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 8,
                            To = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("7f943342-bb5e-4fa8-befb-b165edb0544a"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750148"),
                            From = new DateTime(2022, 8, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 6,
                            To = new DateTime(2022, 8, 11, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("2636530b-2f8e-4462-97bc-b7eab1357ad3"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750139"),
                            From = new DateTime(2022, 8, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 2,
                            To = new DateTime(2022, 8, 12, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("ebd338bd-c00c-44d4-948f-0861a5b7bfe6"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750141"),
                            From = new DateTime(2022, 8, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 6,
                            To = new DateTime(2022, 9, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Departure")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750100"),
                            Departure = "IT",
                            FirstName = "Fname0",
                            LastName = "Lname0",
                            Username = "User0"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750101"),
                            Departure = "Economy",
                            FirstName = "Fname1",
                            LastName = "Lname1",
                            Username = "User1"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750102"),
                            Departure = "Economy",
                            FirstName = "Fname2",
                            LastName = "Lname2",
                            Username = "User2"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750103"),
                            Departure = "IT",
                            FirstName = "Fname3",
                            LastName = "Lname3",
                            Username = "User3"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750104"),
                            Departure = "Economy",
                            FirstName = "Fname4",
                            LastName = "Lname4",
                            Username = "User4"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750105"),
                            Departure = "Economy",
                            FirstName = "Fname5",
                            LastName = "Lname5",
                            Username = "User5"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750106"),
                            Departure = "IT",
                            FirstName = "Fname6",
                            LastName = "Lname6",
                            Username = "User6"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750107"),
                            Departure = "Economy",
                            FirstName = "Fname7",
                            LastName = "Lname7",
                            Username = "User7"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750108"),
                            Departure = "Economy",
                            FirstName = "Fname8",
                            LastName = "Lname8",
                            Username = "User8"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750109"),
                            Departure = "IT",
                            FirstName = "Fname9",
                            LastName = "Lname9",
                            Username = "User9"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750110"),
                            Departure = "Economy",
                            FirstName = "Fname10",
                            LastName = "Lname10",
                            Username = "User10"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750111"),
                            Departure = "Economy",
                            FirstName = "Fname11",
                            LastName = "Lname11",
                            Username = "User11"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750112"),
                            Departure = "IT",
                            FirstName = "Fname12",
                            LastName = "Lname12",
                            Username = "User12"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750113"),
                            Departure = "Economy",
                            FirstName = "Fname13",
                            LastName = "Lname13",
                            Username = "User13"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750114"),
                            Departure = "Economy",
                            FirstName = "Fname14",
                            LastName = "Lname14",
                            Username = "User14"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750115"),
                            Departure = "IT",
                            FirstName = "Fname15",
                            LastName = "Lname15",
                            Username = "User15"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750116"),
                            Departure = "Economy",
                            FirstName = "Fname16",
                            LastName = "Lname16",
                            Username = "User16"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750117"),
                            Departure = "Economy",
                            FirstName = "Fname17",
                            LastName = "Lname17",
                            Username = "User17"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750118"),
                            Departure = "IT",
                            FirstName = "Fname18",
                            LastName = "Lname18",
                            Username = "User18"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750119"),
                            Departure = "Economy",
                            FirstName = "Fname19",
                            LastName = "Lname19",
                            Username = "User19"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750120"),
                            Departure = "Economy",
                            FirstName = "Fname20",
                            LastName = "Lname20",
                            Username = "User20"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750121"),
                            Departure = "IT",
                            FirstName = "Fname21",
                            LastName = "Lname21",
                            Username = "User21"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750122"),
                            Departure = "Economy",
                            FirstName = "Fname22",
                            LastName = "Lname22",
                            Username = "User22"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750123"),
                            Departure = "Economy",
                            FirstName = "Fname23",
                            LastName = "Lname23",
                            Username = "User23"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750124"),
                            Departure = "IT",
                            FirstName = "Fname24",
                            LastName = "Lname24",
                            Username = "User24"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750125"),
                            Departure = "Economy",
                            FirstName = "Fname25",
                            LastName = "Lname25",
                            Username = "User25"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750126"),
                            Departure = "Economy",
                            FirstName = "Fname26",
                            LastName = "Lname26",
                            Username = "User26"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750127"),
                            Departure = "IT",
                            FirstName = "Fname27",
                            LastName = "Lname27",
                            Username = "User27"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750128"),
                            Departure = "Economy",
                            FirstName = "Fname28",
                            LastName = "Lname28",
                            Username = "User28"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750129"),
                            Departure = "Economy",
                            FirstName = "Fname29",
                            LastName = "Lname29",
                            Username = "User29"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750130"),
                            Departure = "IT",
                            FirstName = "Fname30",
                            LastName = "Lname30",
                            Username = "User30"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750131"),
                            Departure = "Economy",
                            FirstName = "Fname31",
                            LastName = "Lname31",
                            Username = "User31"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750132"),
                            Departure = "Economy",
                            FirstName = "Fname32",
                            LastName = "Lname32",
                            Username = "User32"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750133"),
                            Departure = "IT",
                            FirstName = "Fname33",
                            LastName = "Lname33",
                            Username = "User33"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750134"),
                            Departure = "Economy",
                            FirstName = "Fname34",
                            LastName = "Lname34",
                            Username = "User34"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750135"),
                            Departure = "Economy",
                            FirstName = "Fname35",
                            LastName = "Lname35",
                            Username = "User35"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750136"),
                            Departure = "IT",
                            FirstName = "Fname36",
                            LastName = "Lname36",
                            Username = "User36"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750137"),
                            Departure = "Economy",
                            FirstName = "Fname37",
                            LastName = "Lname37",
                            Username = "User37"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750138"),
                            Departure = "Economy",
                            FirstName = "Fname38",
                            LastName = "Lname38",
                            Username = "User38"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750139"),
                            Departure = "IT",
                            FirstName = "Fname39",
                            LastName = "Lname39",
                            Username = "User39"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750140"),
                            Departure = "Economy",
                            FirstName = "Fname40",
                            LastName = "Lname40",
                            Username = "User40"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750141"),
                            Departure = "Economy",
                            FirstName = "Fname41",
                            LastName = "Lname41",
                            Username = "User41"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750142"),
                            Departure = "IT",
                            FirstName = "Fname42",
                            LastName = "Lname42",
                            Username = "User42"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750143"),
                            Departure = "Economy",
                            FirstName = "Fname43",
                            LastName = "Lname43",
                            Username = "User43"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750144"),
                            Departure = "Economy",
                            FirstName = "Fname44",
                            LastName = "Lname44",
                            Username = "User44"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750145"),
                            Departure = "IT",
                            FirstName = "Fname45",
                            LastName = "Lname45",
                            Username = "User45"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750146"),
                            Departure = "Economy",
                            FirstName = "Fname46",
                            LastName = "Lname46",
                            Username = "User46"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750147"),
                            Departure = "Economy",
                            FirstName = "Fname47",
                            LastName = "Lname47",
                            Username = "User47"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750148"),
                            Departure = "IT",
                            FirstName = "Fname48",
                            LastName = "Lname48",
                            Username = "User48"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750149"),
                            Departure = "Economy",
                            FirstName = "Fname49",
                            LastName = "Lname49",
                            Username = "User49"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
