// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ParkingDbContext))]
    [Migration("20220805175055_Add-Hours-To-Reservation-Data")]
    partial class AddHoursToReservationData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("By")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<int>("Shift")
                        .HasColumnType("int");

                    b.Property<int>("Space")
                        .HasColumnType("int");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cebcc7e2-a6fa-4d3a-b72e-a79e1750809f"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750149"),
                            From = new DateTime(2022, 8, 5, 9, 30, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 10,
                            To = new DateTime(2022, 8, 14, 18, 30, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("d6567c3b-ae27-4350-adac-f8884cb90b9e"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750126"),
                            From = new DateTime(2022, 8, 15, 8, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 5,
                            To = new DateTime(2022, 8, 16, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("b91b1cc5-2f56-4282-8fd3-f7e484db6ade"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750125"),
                            From = new DateTime(2022, 9, 3, 14, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 4,
                            To = new DateTime(2022, 9, 4, 21, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("14daabb0-21af-45e4-b509-cd0293879973"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750131"),
                            From = new DateTime(2022, 8, 10, 8, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 9,
                            To = new DateTime(2022, 8, 24, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("76538311-1bc7-41e8-a685-ca3759ba0f11"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750129"),
                            From = new DateTime(2022, 8, 12, 9, 30, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 4,
                            To = new DateTime(2022, 8, 27, 18, 30, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("881c7d73-dc5e-465a-93ff-8b40f4c77b1b"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750146"),
                            From = new DateTime(2022, 8, 11, 9, 30, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 19,
                            To = new DateTime(2022, 8, 28, 18, 30, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("6cdd96de-a5f5-4f01-af55-3dbfd3a15f0e"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750116"),
                            From = new DateTime(2022, 8, 29, 8, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 15,
                            To = new DateTime(2022, 8, 31, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("478ecf71-7153-4ea5-8f94-7b12a1c99822"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750136"),
                            From = new DateTime(2022, 8, 13, 9, 30, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 11,
                            To = new DateTime(2022, 8, 14, 18, 30, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("246572ed-3daf-423f-8bc9-a7c3c7a213bf"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750134"),
                            From = new DateTime(2022, 8, 20, 9, 30, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 12,
                            To = new DateTime(2022, 8, 30, 18, 30, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("c469f538-f298-4f42-b7de-c1b256b88f08"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750112"),
                            From = new DateTime(2022, 8, 5, 14, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 3,
                            To = new DateTime(2022, 8, 22, 21, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("34591429-f740-4029-b723-fd005f1e7378"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750130"),
                            From = new DateTime(2022, 8, 14, 14, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 1,
                            To = new DateTime(2022, 8, 28, 21, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("faba589e-1941-45f0-a782-a76e65149cff"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750100"),
                            From = new DateTime(2022, 8, 20, 14, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 6,
                            To = new DateTime(2022, 8, 27, 21, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("5a94b015-d371-4b44-84d6-ddf56a3df620"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750120"),
                            From = new DateTime(2022, 8, 11, 8, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 16,
                            To = new DateTime(2022, 8, 25, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("38feea54-122d-469a-b944-b0c47a4da2c5"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750139"),
                            From = new DateTime(2022, 8, 23, 8, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 5,
                            To = new DateTime(2022, 8, 26, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("50748ff2-acb7-4eb7-9b24-a68fe58c163e"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750148"),
                            From = new DateTime(2022, 8, 11, 14, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 8,
                            To = new DateTime(2022, 8, 28, 21, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("0339c423-8cb2-4a05-aec5-bb7f9007a39b"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750109"),
                            From = new DateTime(2022, 8, 15, 9, 30, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 7,
                            To = new DateTime(2022, 8, 22, 18, 30, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("a9ba6baa-0592-4e31-8430-8c55bff55f84"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750101"),
                            From = new DateTime(2022, 8, 31, 9, 30, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 3,
                            To = new DateTime(2022, 9, 1, 18, 30, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("c2735411-fa33-4be1-b644-53852fd0a6f3"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750108"),
                            From = new DateTime(2022, 8, 8, 8, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 16,
                            To = new DateTime(2022, 8, 10, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("3de56a22-b238-4bbb-a340-83bbf6f5e783"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750104"),
                            From = new DateTime(2022, 8, 20, 14, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 15,
                            To = new DateTime(2022, 9, 2, 21, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("95161946-6e32-4abc-a534-b08877abc59a"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750141"),
                            From = new DateTime(2022, 8, 19, 9, 30, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 2,
                            To = new DateTime(2022, 9, 4, 18, 30, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("9df7fc53-793d-4465-866c-2d8f387e2639"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750133"),
                            From = new DateTime(2022, 8, 6, 8, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 9,
                            To = new DateTime(2022, 8, 9, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("47b75a41-0684-48e4-8eda-25f45f0c9c13"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750124"),
                            From = new DateTime(2022, 8, 15, 8, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 10,
                            To = new DateTime(2022, 8, 19, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("563abce9-e29d-4f1b-a356-92b42c1ba389"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750144"),
                            From = new DateTime(2022, 8, 29, 9, 30, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 17,
                            To = new DateTime(2022, 9, 3, 18, 30, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("77d1989f-5722-42ca-b4d1-ab781b9c5fc7"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750115"),
                            From = new DateTime(2022, 8, 24, 8, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 17,
                            To = new DateTime(2022, 8, 25, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("7fa95862-7a87-4ef8-8c7d-628e7ccc678b"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750123"),
                            From = new DateTime(2022, 8, 24, 14, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 11,
                            To = new DateTime(2022, 9, 4, 21, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("f2d8b4f4-92e8-42dc-856e-092c74b0b66c"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750128"),
                            From = new DateTime(2022, 8, 11, 14, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 18,
                            To = new DateTime(2022, 8, 17, 21, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("0a8412f5-6347-449b-a001-eeeed845c528"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750140"),
                            From = new DateTime(2022, 8, 23, 14, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 17,
                            To = new DateTime(2022, 8, 24, 21, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("d2bbaf29-9f09-4ac6-ac26-ecd939baa27a"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750119"),
                            From = new DateTime(2022, 8, 7, 8, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 1,
                            To = new DateTime(2022, 8, 31, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("79693a45-ce1b-4ef7-8c8f-772769e345a6"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750106"),
                            From = new DateTime(2022, 8, 7, 9, 30, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 12,
                            To = new DateTime(2022, 8, 15, 18, 30, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("68677843-16d1-451b-909b-11a4fe0b10cf"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750114"),
                            From = new DateTime(2022, 8, 28, 8, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 18,
                            To = new DateTime(2022, 9, 1, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("6f64d646-01f4-4fe1-9b7a-7cfe990bf271"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750145"),
                            From = new DateTime(2022, 8, 19, 8, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 14,
                            To = new DateTime(2022, 8, 30, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("ac00768d-b49c-4a11-b2d7-efabcdaef3a2"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750110"),
                            From = new DateTime(2022, 8, 15, 14, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 13,
                            To = new DateTime(2022, 8, 18, 21, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("24576c42-ecb2-4fb2-9b84-70702d63dd60"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750103"),
                            From = new DateTime(2022, 8, 5, 9, 30, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 20,
                            To = new DateTime(2022, 8, 20, 18, 30, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("d74777a9-9af0-46ae-9c91-6c50e5f71799"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750102"),
                            From = new DateTime(2022, 8, 10, 8, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 17,
                            To = new DateTime(2022, 8, 22, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("585ad9b5-a5db-428a-9f1d-f578b318edba"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750127"),
                            From = new DateTime(2022, 8, 24, 14, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 14,
                            To = new DateTime(2022, 9, 4, 21, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("7bc71406-060a-4718-9c96-a51ab07f733f"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750138"),
                            From = new DateTime(2022, 8, 5, 8, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 13,
                            To = new DateTime(2022, 8, 16, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("f8bce87b-d0f7-4b14-a1fd-1b96f1f9e382"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750117"),
                            From = new DateTime(2022, 8, 20, 8, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 6,
                            To = new DateTime(2022, 8, 29, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("60d32f25-bd7c-46ce-bdd4-6e6e1bf1c5aa"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750122"),
                            From = new DateTime(2022, 8, 10, 8, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 8,
                            To = new DateTime(2022, 8, 28, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("ccb777aa-175a-44ed-bf0f-bd9110143005"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750132"),
                            From = new DateTime(2022, 8, 12, 14, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 5,
                            To = new DateTime(2022, 8, 27, 21, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("c0d29a3a-dc74-46cd-8067-7a11fab8fb46"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750135"),
                            From = new DateTime(2022, 8, 16, 8, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 18,
                            To = new DateTime(2022, 8, 23, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("7f700768-1236-4432-b043-3d6723267721"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750113"),
                            From = new DateTime(2022, 8, 7, 9, 30, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 19,
                            To = new DateTime(2022, 8, 9, 18, 30, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("46eafc3f-40a9-4919-9e13-4cac08276096"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750105"),
                            From = new DateTime(2022, 8, 27, 8, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 10,
                            To = new DateTime(2022, 9, 2, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("ea75a917-4bb1-41c8-aaf1-b329cb36b8ed"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750143"),
                            From = new DateTime(2022, 8, 7, 8, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 7,
                            To = new DateTime(2022, 8, 13, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("11814051-a95a-45aa-9484-cd5f4e1caccd"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750137"),
                            From = new DateTime(2022, 8, 20, 14, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 16,
                            To = new DateTime(2022, 8, 21, 21, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("1588525b-70cb-4342-9ce1-1a6db99002cc"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750107"),
                            From = new DateTime(2022, 8, 16, 9, 30, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 14,
                            To = new DateTime(2022, 8, 17, 18, 30, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("2c26a01f-da47-4c6c-8a39-7f8787d34c4d"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750142"),
                            From = new DateTime(2022, 8, 13, 14, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 15,
                            To = new DateTime(2022, 8, 15, 21, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("a7251529-413a-4de4-bdfe-68f963769efd"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750118"),
                            From = new DateTime(2022, 8, 23, 9, 30, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 20,
                            To = new DateTime(2022, 8, 29, 18, 30, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("e6545642-a1c8-43d2-bef0-06ca3437a657"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750147"),
                            From = new DateTime(2022, 8, 24, 8, 0, 0, 0, DateTimeKind.Local),
                            Shift = 1,
                            Space = 11,
                            To = new DateTime(2022, 9, 4, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("ec989c36-0ddf-4b41-a231-c62fc27e72cf"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750111"),
                            From = new DateTime(2022, 8, 26, 14, 0, 0, 0, DateTimeKind.Local),
                            Shift = 2,
                            Space = 9,
                            To = new DateTime(2022, 8, 28, 21, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("429f9292-8cf1-4921-a9ac-aac17b9db8c8"),
                            By = new Guid("4c33537b-e856-463b-811e-e8e059750121"),
                            From = new DateTime(2022, 8, 25, 9, 30, 0, 0, DateTimeKind.Local),
                            Shift = 3,
                            Space = 13,
                            To = new DateTime(2022, 8, 29, 18, 30, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Departure")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750100"),
                            Departure = "IT",
                            FirstName = "Fname0",
                            LastName = "Lname0",
                            Username = "User0"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750101"),
                            Departure = "Economy",
                            FirstName = "Fname1",
                            LastName = "Lname1",
                            Username = "User1"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750102"),
                            Departure = "Economy",
                            FirstName = "Fname2",
                            LastName = "Lname2",
                            Username = "User2"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750103"),
                            Departure = "IT",
                            FirstName = "Fname3",
                            LastName = "Lname3",
                            Username = "User3"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750104"),
                            Departure = "Economy",
                            FirstName = "Fname4",
                            LastName = "Lname4",
                            Username = "User4"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750105"),
                            Departure = "Economy",
                            FirstName = "Fname5",
                            LastName = "Lname5",
                            Username = "User5"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750106"),
                            Departure = "IT",
                            FirstName = "Fname6",
                            LastName = "Lname6",
                            Username = "User6"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750107"),
                            Departure = "Economy",
                            FirstName = "Fname7",
                            LastName = "Lname7",
                            Username = "User7"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750108"),
                            Departure = "Economy",
                            FirstName = "Fname8",
                            LastName = "Lname8",
                            Username = "User8"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750109"),
                            Departure = "IT",
                            FirstName = "Fname9",
                            LastName = "Lname9",
                            Username = "User9"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750110"),
                            Departure = "Economy",
                            FirstName = "Fname10",
                            LastName = "Lname10",
                            Username = "User10"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750111"),
                            Departure = "Economy",
                            FirstName = "Fname11",
                            LastName = "Lname11",
                            Username = "User11"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750112"),
                            Departure = "IT",
                            FirstName = "Fname12",
                            LastName = "Lname12",
                            Username = "User12"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750113"),
                            Departure = "Economy",
                            FirstName = "Fname13",
                            LastName = "Lname13",
                            Username = "User13"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750114"),
                            Departure = "Economy",
                            FirstName = "Fname14",
                            LastName = "Lname14",
                            Username = "User14"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750115"),
                            Departure = "IT",
                            FirstName = "Fname15",
                            LastName = "Lname15",
                            Username = "User15"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750116"),
                            Departure = "Economy",
                            FirstName = "Fname16",
                            LastName = "Lname16",
                            Username = "User16"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750117"),
                            Departure = "Economy",
                            FirstName = "Fname17",
                            LastName = "Lname17",
                            Username = "User17"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750118"),
                            Departure = "IT",
                            FirstName = "Fname18",
                            LastName = "Lname18",
                            Username = "User18"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750119"),
                            Departure = "Economy",
                            FirstName = "Fname19",
                            LastName = "Lname19",
                            Username = "User19"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750120"),
                            Departure = "Economy",
                            FirstName = "Fname20",
                            LastName = "Lname20",
                            Username = "User20"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750121"),
                            Departure = "IT",
                            FirstName = "Fname21",
                            LastName = "Lname21",
                            Username = "User21"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750122"),
                            Departure = "Economy",
                            FirstName = "Fname22",
                            LastName = "Lname22",
                            Username = "User22"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750123"),
                            Departure = "Economy",
                            FirstName = "Fname23",
                            LastName = "Lname23",
                            Username = "User23"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750124"),
                            Departure = "IT",
                            FirstName = "Fname24",
                            LastName = "Lname24",
                            Username = "User24"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750125"),
                            Departure = "Economy",
                            FirstName = "Fname25",
                            LastName = "Lname25",
                            Username = "User25"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750126"),
                            Departure = "Economy",
                            FirstName = "Fname26",
                            LastName = "Lname26",
                            Username = "User26"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750127"),
                            Departure = "IT",
                            FirstName = "Fname27",
                            LastName = "Lname27",
                            Username = "User27"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750128"),
                            Departure = "Economy",
                            FirstName = "Fname28",
                            LastName = "Lname28",
                            Username = "User28"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750129"),
                            Departure = "Economy",
                            FirstName = "Fname29",
                            LastName = "Lname29",
                            Username = "User29"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750130"),
                            Departure = "IT",
                            FirstName = "Fname30",
                            LastName = "Lname30",
                            Username = "User30"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750131"),
                            Departure = "Economy",
                            FirstName = "Fname31",
                            LastName = "Lname31",
                            Username = "User31"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750132"),
                            Departure = "Economy",
                            FirstName = "Fname32",
                            LastName = "Lname32",
                            Username = "User32"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750133"),
                            Departure = "IT",
                            FirstName = "Fname33",
                            LastName = "Lname33",
                            Username = "User33"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750134"),
                            Departure = "Economy",
                            FirstName = "Fname34",
                            LastName = "Lname34",
                            Username = "User34"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750135"),
                            Departure = "Economy",
                            FirstName = "Fname35",
                            LastName = "Lname35",
                            Username = "User35"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750136"),
                            Departure = "IT",
                            FirstName = "Fname36",
                            LastName = "Lname36",
                            Username = "User36"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750137"),
                            Departure = "Economy",
                            FirstName = "Fname37",
                            LastName = "Lname37",
                            Username = "User37"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750138"),
                            Departure = "Economy",
                            FirstName = "Fname38",
                            LastName = "Lname38",
                            Username = "User38"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750139"),
                            Departure = "IT",
                            FirstName = "Fname39",
                            LastName = "Lname39",
                            Username = "User39"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750140"),
                            Departure = "Economy",
                            FirstName = "Fname40",
                            LastName = "Lname40",
                            Username = "User40"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750141"),
                            Departure = "Economy",
                            FirstName = "Fname41",
                            LastName = "Lname41",
                            Username = "User41"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750142"),
                            Departure = "IT",
                            FirstName = "Fname42",
                            LastName = "Lname42",
                            Username = "User42"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750143"),
                            Departure = "Economy",
                            FirstName = "Fname43",
                            LastName = "Lname43",
                            Username = "User43"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750144"),
                            Departure = "Economy",
                            FirstName = "Fname44",
                            LastName = "Lname44",
                            Username = "User44"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750145"),
                            Departure = "IT",
                            FirstName = "Fname45",
                            LastName = "Lname45",
                            Username = "User45"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750146"),
                            Departure = "Economy",
                            FirstName = "Fname46",
                            LastName = "Lname46",
                            Username = "User46"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750147"),
                            Departure = "Economy",
                            FirstName = "Fname47",
                            LastName = "Lname47",
                            Username = "User47"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750148"),
                            Departure = "IT",
                            FirstName = "Fname48",
                            LastName = "Lname48",
                            Username = "User48"
                        },
                        new
                        {
                            Id = new Guid("4c33537b-e856-463b-811e-e8e059750149"),
                            Departure = "Economy",
                            FirstName = "Fname49",
                            LastName = "Lname49",
                            Username = "User49"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
