// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations.AuthDb
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20220805190047_Add-Better-Password-Seeding")]
    partial class AddBetterPasswordSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750100",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9d72e767-8f4b-41df-b851-ebac0236bc1a",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER0",
                            PasswordHash = "AQAAAAEAACcQAAAAEHVRuttXOlibeu2Zk6FzLsqpdApLJGSILxSzv6MSDsxORlBdUGeBWI6FBqp69IR6Nw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e70198d6-395c-496d-b736-67ecb3362eab",
                            TwoFactorEnabled = false,
                            UserName = "User0"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750101",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1bc5f76e-cc11-4eae-b509-a4a320d8b9c6",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER1",
                            PasswordHash = "AQAAAAEAACcQAAAAECfdSfEQyo1xvxo+bYZjFiabRUY3SnSiodlZg3TmYHSK4+KZF1CE4HfP6MOoiTq8Mw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b35e49ea-6b55-47e8-a8a2-5d1dc75874be",
                            TwoFactorEnabled = false,
                            UserName = "User1"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750102",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0ebc1bc5-2263-4c4d-a861-47d4fe01bf79",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER2",
                            PasswordHash = "AQAAAAEAACcQAAAAECXnE70n6jp0Z2k/7uet1QZrD5HzHdx2QiGDtUCXEAR4ejw2dM6eahyVZuKXmw0bEA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bf4fb43d-0d75-4f8b-b383-901931dbc380",
                            TwoFactorEnabled = false,
                            UserName = "User2"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750103",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1270f939-a13d-4c7e-afb4-f60b070fc773",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER3",
                            PasswordHash = "AQAAAAEAACcQAAAAEOXU51eQ/i5pCDSDn8LFgZZR02w+fphWYM0uEuGLd9/1tQNZlQ1ngMjRW757/yeuNw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c5ffc3fa-3c42-4b60-beaa-0d996b36f8b0",
                            TwoFactorEnabled = false,
                            UserName = "User3"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750104",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "17669663-9775-45b0-a1bd-c76496bd6d68",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER4",
                            PasswordHash = "AQAAAAEAACcQAAAAEE5Yt6I2xdKDb0LNAfm+IPzKMIPy79PGnaUEAhCvfWjT8nDlmBQFJ/mcnR6s98rPFA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "076fe6f3-aeef-4264-b804-3c5297ba61c4",
                            TwoFactorEnabled = false,
                            UserName = "User4"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750105",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c16c2a3b-743f-4cf1-bc69-54b2c17d3b36",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER5",
                            PasswordHash = "AQAAAAEAACcQAAAAEI9om9rmcvgZBTyjLyFBwnJ8HUlNC9bx29NSyU6TTLqWwjHeS/yKwmoOpWrR+mBBOQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f9c259fe-66fd-4549-ae12-69bde91a451d",
                            TwoFactorEnabled = false,
                            UserName = "User5"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750106",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "61a77c1e-66d9-4a02-9741-10592530fc38",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER6",
                            PasswordHash = "AQAAAAEAACcQAAAAEANn5FF5+ojXRTBI2lewQKaUPy79pnY9GtLptmNbjzeqEuV8UcCR3zlCd/eFb5E/Lg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f5c691eb-f5ce-4ebc-9fb1-1a265b2b93b9",
                            TwoFactorEnabled = false,
                            UserName = "User6"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750107",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a4e6bc4a-046a-44a9-bd38-3cd8c995cabc",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER7",
                            PasswordHash = "AQAAAAEAACcQAAAAEOeQ/omgv3yW93FPfWlRAS+4yQkm0hwDLbRf14WNNxHH5se6TlgdxglvshFUjcHMOg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "49ef5ed1-7b72-4645-8790-683758be7d74",
                            TwoFactorEnabled = false,
                            UserName = "User7"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750108",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dd42f8a9-bb88-44aa-b9f2-5d24c9b38436",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER8",
                            PasswordHash = "AQAAAAEAACcQAAAAEKHhmQQEYVyJ3kDJGBDkVrLYmbDHZCvbJR6LEcXIjFqpBKiLX1rH7faUWL8aLjAucA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c9bef373-de84-4e6d-9d60-600904355444",
                            TwoFactorEnabled = false,
                            UserName = "User8"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750109",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b90c3874-63da-4b1a-98cb-68be73c75668",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER9",
                            PasswordHash = "AQAAAAEAACcQAAAAEAfVtdg07/Yep8edbdWk8Kh7NH4MudanhKC5f+eEb+3PZXYqLixNuyKj06scxUQr5A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3d871def-dc82-4eb7-b54d-5f1bd004f966",
                            TwoFactorEnabled = false,
                            UserName = "User9"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750110",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0dfe1852-44ba-4c85-9271-40ab3b800f83",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER10",
                            PasswordHash = "AQAAAAEAACcQAAAAECqZFyB2Z+TYQSiZ0eD2wUjK2nJREUSQKfsVkQx1qFwdc6Zt3WXNf8xOQhVJJUtJXg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "33976e07-d389-47cf-8945-f4b9590a49ad",
                            TwoFactorEnabled = false,
                            UserName = "User10"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "729ae243-afb7-49f8-88f5-653546fa57b2",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER11",
                            PasswordHash = "AQAAAAEAACcQAAAAEA8wrklGU94cOMIg1Ygdfg0WoskKKPhkXhQh61DYFJDNwqNQpwojo6QiTwNXT1WMwQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5b5dc696-9fbc-4ca9-a2c3-8305e014e865",
                            TwoFactorEnabled = false,
                            UserName = "User11"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750112",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c12503ff-e251-48fd-9653-ec6af081d551",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER12",
                            PasswordHash = "AQAAAAEAACcQAAAAEO8PU+5Ow/JO8eHO20FJ6+gu49e3yR0iizE3K2hSwfQesBgfBH0XThMKqqRhqSxLsg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "69d28dc0-0b6f-4047-8435-bbd6a981f444",
                            TwoFactorEnabled = false,
                            UserName = "User12"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750113",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7e4542ea-870e-4110-a6b5-3ff8872a92ee",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER13",
                            PasswordHash = "AQAAAAEAACcQAAAAEJApVWRyFhrZ/M9zbAtb3YVxyZCfPqwv1w9vtsNeM97+a3SGW8tWcYue/ULiusD21w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4c00539f-46d7-4d73-82e9-ed0079d4ad14",
                            TwoFactorEnabled = false,
                            UserName = "User13"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750114",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "da68a79e-1196-4865-b2a3-536c5d9f4ef9",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER14",
                            PasswordHash = "AQAAAAEAACcQAAAAEKOmz8BSy8jan0eFFnsh0fNMYlNYLoLx25TTeSK248r787yrxbUEIiPIHJATDKFtUA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e3d54fbf-0b6c-4189-ae98-df33e0914898",
                            TwoFactorEnabled = false,
                            UserName = "User14"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750115",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "57bedba3-4642-4323-9566-2557b19fe043",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER15",
                            PasswordHash = "AQAAAAEAACcQAAAAEJvLhtZd74l2oVL7bOXc9cANT4TdPtfhehzvJ/Eh+mmzshRe5nw79gu+VaRbsOjt3w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2238fae0-6b29-475a-9b8b-a3e24a926cb7",
                            TwoFactorEnabled = false,
                            UserName = "User15"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750116",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f144456c-fece-4bfe-aa88-837752f17957",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER16",
                            PasswordHash = "AQAAAAEAACcQAAAAEJiMRvt+1hxCD31LV0JmdqaUpC4gJKTqQZwSc0iRXWzRIkv0jCDUmm3gr+nDD3l4sg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d5e560f0-a48f-42b1-837c-2613f7d66187",
                            TwoFactorEnabled = false,
                            UserName = "User16"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750117",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "676d4937-b90d-45c0-9e4f-c74a80c7fd11",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER17",
                            PasswordHash = "AQAAAAEAACcQAAAAEETHHvKrt8hIiBGConqadUvlVBCqGcTdujqcGLqZ8n8j9CA0lH170iIL9saJWvBq6w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7616475c-4ce1-4a0b-be0b-62a12af89f17",
                            TwoFactorEnabled = false,
                            UserName = "User17"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750118",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "203d1625-2648-46e5-ad3b-b2d6ebcf49ab",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER18",
                            PasswordHash = "AQAAAAEAACcQAAAAEBQLb2271bqolemuQUyRujNQEYQM8gU7kiZAB0ofr/i8Y5HWH6wynvGPpPfP/2P4MQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d10b5e5a-03db-413a-b445-1a72620bcf3a",
                            TwoFactorEnabled = false,
                            UserName = "User18"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750119",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "66441d87-907d-45a6-877e-0e0ad6afb059",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER19",
                            PasswordHash = "AQAAAAEAACcQAAAAELSPu2Rz/HSp43NqSy12P3dXM9IwRxVxLtf6msIJL/3O3lLwD9tj4qv7Vds4usKmOA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1ad47c72-35df-4350-8a43-93f15d5a3a97",
                            TwoFactorEnabled = false,
                            UserName = "User19"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750120",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f4a98d81-eeae-482e-bac4-803a2d988e27",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER20",
                            PasswordHash = "AQAAAAEAACcQAAAAEMknHlWrbpTU1nzGFZahzkzmD5CBRR/nLEAqcgBnMmMPMS103IltXmAnwNlQcohMDQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9ec523cf-429b-43dd-9267-32fbae83287b",
                            TwoFactorEnabled = false,
                            UserName = "User20"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750121",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5a28c7b6-b039-4f10-8b3b-03a6f78a2479",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER21",
                            PasswordHash = "AQAAAAEAACcQAAAAEGI5CvV5gP5mZSDF9BSWQ/WeAHM4/O3L1Xd79W8TAZAElAPofB+Nrwgw5R3j0lBkcg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ba91cc07-2744-43d4-b282-249d06420803",
                            TwoFactorEnabled = false,
                            UserName = "User21"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750122",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b844b9e4-e8a8-4f79-ae1c-de311d8148ff",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER22",
                            PasswordHash = "AQAAAAEAACcQAAAAEJ1GKwCQIi3xcPDFltbBxOUjpkLRchYgOBMyU/FXYH21AvsLkDYTl3M2R02aN4oqfg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c5af9818-f276-4a2b-b7ed-5e05ba7350b7",
                            TwoFactorEnabled = false,
                            UserName = "User22"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750123",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7b5dc424-6962-4c0b-8c75-f8e244819dfd",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER23",
                            PasswordHash = "AQAAAAEAACcQAAAAEBHQCHufByMxqABFmyPZDC5ZhQk5P4OMxDwfTrCPjiRATOspN1QG/LW2yy9+da1Qmw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2fede8b6-4f84-4d58-a70d-e7d46c537ad8",
                            TwoFactorEnabled = false,
                            UserName = "User23"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750124",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9522982f-4eba-48ee-ae18-67ce4eeee054",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER24",
                            PasswordHash = "AQAAAAEAACcQAAAAEPlY5Bbg9kX4D1gt88EuRYz+H4GS6CZvtLT3oUD+NsCKavbcPHuz1cpj8THGmSI1Fw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "71b837f0-fb9d-44d0-ba5b-804063208ad4",
                            TwoFactorEnabled = false,
                            UserName = "User24"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750125",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "10693908-e6a1-4cbe-ae32-4fdc772eb56a",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER25",
                            PasswordHash = "AQAAAAEAACcQAAAAEA1VlHaTghuUkDHNeigaFOF3fNiAntFcgg5ZSP//yzAUNhByB5xA7iBRoqlJeQDOow==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d7b0766f-f257-4e98-a18d-838edfbd5d72",
                            TwoFactorEnabled = false,
                            UserName = "User25"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750126",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "190d22de-2977-4d78-ac01-c8dbeed3b08d",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER26",
                            PasswordHash = "AQAAAAEAACcQAAAAEFfO0ThWjtIoxmD40cTMgpXRVGdPbnyw6C0LOgrmHKBsNavHdv4bR4hjoU4GQpM1NQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ae4bdae1-7b33-4307-8395-d2a6a98aef9b",
                            TwoFactorEnabled = false,
                            UserName = "User26"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750127",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0b86acc8-0032-4ec8-b427-e8ffef0a1da3",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER27",
                            PasswordHash = "AQAAAAEAACcQAAAAELVoPH/3NhbopIp9QhCYma0CfhH68Mz+9PawBKG50EEZuKqT01nymXEJy6iT0gU4tQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "aac5a11c-81cd-4f98-ba8c-15cf521cf7b6",
                            TwoFactorEnabled = false,
                            UserName = "User27"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750128",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5d19832c-b0b7-4876-973a-6ea02d0c8eed",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER28",
                            PasswordHash = "AQAAAAEAACcQAAAAEPrxmJCrmKwjaZlT9+nFdRhZs/fvLBjZq6UR1po3k0CrdL4+GQkiac+3ys1Xk/DxHg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "37834097-2354-4bf0-b10d-786e34bd0fdf",
                            TwoFactorEnabled = false,
                            UserName = "User28"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750129",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ebff9bce-6cc0-4e65-8acb-8544091b44a1",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER29",
                            PasswordHash = "AQAAAAEAACcQAAAAEM+RHBMsSHPBTIbcQZ65uCQG7WUAbuA9+VhdjHdgXYsylODebGU/xrzIu9G68jjH6A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7f9aa552-10d9-4720-8c99-f53fa1cb3241",
                            TwoFactorEnabled = false,
                            UserName = "User29"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750130",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "53bb64ea-1264-4185-8089-937bd5449b64",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER30",
                            PasswordHash = "AQAAAAEAACcQAAAAENiGDz8k1Jbucd2HkMnyzMLsK4pazR5kZXXyM7dHtmlW/zIrCoCWicvK3URLBle2+A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "74be2926-6533-43c9-9f51-9c687f586cea",
                            TwoFactorEnabled = false,
                            UserName = "User30"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750131",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5dcb6123-c38c-4e43-8a1c-eeb1d4d2f4d5",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER31",
                            PasswordHash = "AQAAAAEAACcQAAAAEGMlXL5lptmZ19qlKJcSRXzAb9mHzy06ky3seVWSKNLMQBtoajeNMbD4DsmZcr5y0Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "356ae703-cde4-4e84-ba12-e87df3398bbc",
                            TwoFactorEnabled = false,
                            UserName = "User31"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750132",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "57154bb1-b9ea-4a94-b178-1e6354cdc938",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER32",
                            PasswordHash = "AQAAAAEAACcQAAAAEH0popZlGX0hRDZn27bBnsF7ttQFi0gm/6Xrgme3Xfwc2RMSGLOsZcP4aM2qEdu/6A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0317d981-a359-4289-b403-cb86fcf838b6",
                            TwoFactorEnabled = false,
                            UserName = "User32"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750133",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "69a64edd-4825-4d10-acb7-e3983364190c",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER33",
                            PasswordHash = "AQAAAAEAACcQAAAAEDZ0ZTsmgdLX8DWvMCUM7toseRf7/RhF5SmMXAt25iA9QaIfqv3DzD+DyodnxzeU5A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "39964437-1ddf-49cb-a731-34fbe10d9d99",
                            TwoFactorEnabled = false,
                            UserName = "User33"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750134",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "936080c7-24e7-4a72-ba17-2635e9a3db41",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER34",
                            PasswordHash = "AQAAAAEAACcQAAAAEAtVqK95GXmjkNqZ0cW22vtOiZIh1teyui4F6UIst6BN2FEhe8Ew33q2pg+EuMmnww==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "39ee6894-3ce6-4753-8df9-92bd1b5f0f78",
                            TwoFactorEnabled = false,
                            UserName = "User34"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750135",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7517e1bd-fe19-4c11-8ac9-02935785f834",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER35",
                            PasswordHash = "AQAAAAEAACcQAAAAELE4Rj+DEX5TLx8Y9ZaUheTVGKF4MVjV2vsKzjC9BGMsiC3oNkJAHTrGcJBvnB55IA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "16ccc471-95aa-439c-8077-b7c5ff024c61",
                            TwoFactorEnabled = false,
                            UserName = "User35"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750136",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7c383961-2b07-4548-b079-cfd7a44dbb72",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER36",
                            PasswordHash = "AQAAAAEAACcQAAAAEOIVjlzWo00665dhOEy9U8ugssW0UT45swugmZS1Jgfmwg1COFgEI8nMp6mJP3w+rA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "272aff6d-95a7-4524-bf93-baec9db65a44",
                            TwoFactorEnabled = false,
                            UserName = "User36"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750137",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "27a69712-f844-4af0-a914-1e79c8cccb6d",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER37",
                            PasswordHash = "AQAAAAEAACcQAAAAEBlsEmxpn/wxYQohAGg9ZGFHEYVskT6kxxewI3bkBAvRc2djF+1JFBQd/baD+giWyg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "21cb1240-4aac-492c-a196-3f732f23fc58",
                            TwoFactorEnabled = false,
                            UserName = "User37"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750138",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "93467fde-0ce5-4fe2-a23c-723f63710309",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER38",
                            PasswordHash = "AQAAAAEAACcQAAAAECEGo1fZqN1bzcQ939H6jxFub1DH4BSgTJGOqI+DgpXoq+gMd5zMVxOaipoifFLoxw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f95c3f99-5dc7-4766-be02-47ac291de8d8",
                            TwoFactorEnabled = false,
                            UserName = "User38"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750139",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "83ea7b4a-f4be-4939-a68c-23a890c73beb",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER39",
                            PasswordHash = "AQAAAAEAACcQAAAAEKqMLJcxka4v+n4Len0gC1TqeU+wnXi4KEWyL1f3rPMcEKXB9CIroO7c3wgcBA+0Wg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9f5dbfd3-9f7b-45d5-bd56-5fea7453018c",
                            TwoFactorEnabled = false,
                            UserName = "User39"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750140",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "77a7120e-fb62-4105-b1b3-32f5d4e07969",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER40",
                            PasswordHash = "AQAAAAEAACcQAAAAEHerJ28tkUdEZwQdTGSOuZkxjrcGghiyqFZim9ffPdTp/Tlo8JS9MOd63YLLYfm0tw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "70745895-152d-46d8-8eea-568d6dfdcf02",
                            TwoFactorEnabled = false,
                            UserName = "User40"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750141",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "78801e00-49a2-4159-8394-75b6bdb81f49",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER41",
                            PasswordHash = "AQAAAAEAACcQAAAAEOlDM9QShAlqcmgfQIG2+izRy0Ik0U6C4optK9HximY/I35ftbzAh+NHEqgMPWFzvw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b17c1bdc-cc9c-480c-b03c-d4694e7cb77b",
                            TwoFactorEnabled = false,
                            UserName = "User41"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750142",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0f7a4b61-8537-4b55-aade-9bad1cdb71d6",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER42",
                            PasswordHash = "AQAAAAEAACcQAAAAEJb6XOigAA/NBhulKdcLGjYw84kVjfD9wXy5DVEcoBauM0XRiFkLY4AJx2T1zCzWgg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "524e9994-8fe6-44f0-8b43-5104a9ec569a",
                            TwoFactorEnabled = false,
                            UserName = "User42"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750143",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "04a10128-4e02-4c6e-8c6a-4d2860f19dae",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER43",
                            PasswordHash = "AQAAAAEAACcQAAAAEGiMUwD6TIIxD6HbvbnRT5T3dpXcz6tZCHvbcRRqbJ+PM835BJ2ATl9pnKKuKBQuOA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6bfa69df-3934-4941-b50d-eefbbf859cb4",
                            TwoFactorEnabled = false,
                            UserName = "User43"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750144",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8d36895b-f4ad-4e8c-b164-84253da678ee",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER44",
                            PasswordHash = "AQAAAAEAACcQAAAAEHbl+TL3QbkvNHyWeS6vuiTT6vzhsyXrJpcr1ntVRbon1cQARrSSkKHcnlhPI5nqzg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7d639554-e862-40d2-a8ae-86427d84afca",
                            TwoFactorEnabled = false,
                            UserName = "User44"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750145",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f7816822-96ef-4c3e-9937-73672e553496",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER45",
                            PasswordHash = "AQAAAAEAACcQAAAAEPBAEQ5KIx39Xs+d+dDE7PhSbCjnd3H6WCjl1UCjk5k5tD7jYgHvK0Tog4rrPzyZ2w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bb94e65b-bace-41af-86be-7cc2430f8766",
                            TwoFactorEnabled = false,
                            UserName = "User45"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750146",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e8368238-f27f-45ac-bbf6-6f9b5fc6857c",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER46",
                            PasswordHash = "AQAAAAEAACcQAAAAEPVJ0qHSU7f9+D2l89Iyimg3Palh86idHeN58zRAnUKIm/uiVEVLJfpoGanedfdtQA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5a4bb786-e93a-49db-9cdc-ec29aca746d6",
                            TwoFactorEnabled = false,
                            UserName = "User46"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750147",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "93858cbf-ec63-45d2-adac-15ef4dea9e2a",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER47",
                            PasswordHash = "AQAAAAEAACcQAAAAEB9ewIwPm00kMA7at7KX0BeM1RNbnVgmPj/yHEVXMRITed8sMYe5G50WRzHCNNxHfg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "24402b56-3f90-4a86-8130-d037bd701626",
                            TwoFactorEnabled = false,
                            UserName = "User47"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750148",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "531c16c8-fb87-4cca-9aed-f9edcab63d62",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER48",
                            PasswordHash = "AQAAAAEAACcQAAAAEIgsVEuK+2PV61+4uxDTS6iG5KXxg8TXVJGFC3AHI+yGfmeD0TwnXCOB+EH8hKNodg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "677dc5ed-c489-425e-9d88-522aeedf238b",
                            TwoFactorEnabled = false,
                            UserName = "User48"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750149",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1a1dcb20-7071-4868-bec6-2f19ae0a5e14",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER49",
                            PasswordHash = "AQAAAAEAACcQAAAAELRHbrvcAKaw4S1MkJKRzmOyh+bKrrvRdpPAunOQ0MixwNMrV3kB3if1W1UAENelQA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "38f44dae-0dc1-41fe-a36c-9366e4647ea7",
                            TwoFactorEnabled = false,
                            UserName = "User49"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
