// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations.AuthDb
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20220805125112_Add-Identity-Seeding")]
    partial class AddIdentitySeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750100",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "def5f381-8bd7-411a-96bd-24cf7e483943",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER0",
                            PasswordHash = "AQAAAAEAACcQAAAAEKz+ICfYoZH4U3z0ULoLtbMWLW6xir2QzqOw008j1Q80ZBa9I/DnAGiNEW+rr/ORYA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ef890307-cd3a-4214-8812-73eba8c16faf",
                            TwoFactorEnabled = false,
                            UserName = "User0"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750101",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "10a300b1-9224-4af1-aff3-07bd7b56b2e1",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER1",
                            PasswordHash = "AQAAAAEAACcQAAAAEA0jyd8dQoGyhuM/zNN6tHKmmh68Gnm+pcBBYchYvbXYVRbVgYEzxzPXhSaMu0fA0g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2abfe258-2acd-4e99-a273-698fd526bc37",
                            TwoFactorEnabled = false,
                            UserName = "User1"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750102",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c1543d87-8261-4f72-8d03-295d60ec83fc",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER2",
                            PasswordHash = "AQAAAAEAACcQAAAAENwdMuc7gXEK2CfUzEyNPwonLyR+mM1HojsHf69RW5Atzzq7fQ4XbFjJYJMLTpE47w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e2c59100-ebef-4bc0-ac4e-563702ae9782",
                            TwoFactorEnabled = false,
                            UserName = "User2"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750103",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ae3b2cc3-55b3-4bcf-89d3-0de54f39ca10",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER3",
                            PasswordHash = "AQAAAAEAACcQAAAAELLlGQat9QSWxo3AUEYS1Ow1mR18+oiOcVXc9tilHYZXz+nnQBy9wMT8IH5xoeht9Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0319e2a6-71a8-46c7-ba16-bbd6a8f84441",
                            TwoFactorEnabled = false,
                            UserName = "User3"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750104",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f57e3413-7d42-47a7-9542-5ec940a6bedc",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER4",
                            PasswordHash = "AQAAAAEAACcQAAAAEKVy81o3R9+mfNXdReDlBEBCbuz1zGIDxQcJC85NunMNO9un+VdfTQG8RMkTlUi1JQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a433435e-0941-4cfd-9066-d42f3343c1c2",
                            TwoFactorEnabled = false,
                            UserName = "User4"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750105",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f3f5601d-1491-4801-bba5-b89fbb7715ad",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER5",
                            PasswordHash = "AQAAAAEAACcQAAAAEDeTc6y5oQzadX2ngg2kIHlYKGNJr4lWIPGQRtq1lxgGFSGNoUKH2+3xymVVhqFHyA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8dd6632d-5be1-401b-bbb5-a60d96570f32",
                            TwoFactorEnabled = false,
                            UserName = "User5"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750106",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "28f0f467-0f28-46e8-b267-4198a0c6d5d3",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER6",
                            PasswordHash = "AQAAAAEAACcQAAAAED48cutvOeSKIcP5bg1sHRPOE+6pDz07nZuxBjhxONi4tJS5DhJk4B/BaXI6NOrcRw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "22eadf52-39dc-4ed0-8526-64316a952b45",
                            TwoFactorEnabled = false,
                            UserName = "User6"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750107",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e19c3dcd-c6c1-4193-a87b-bb5db7103c89",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER7",
                            PasswordHash = "AQAAAAEAACcQAAAAEA7/AijF3fOM0JNf7Qn4poyBelMuqwYFSe9VYlcWh3sLVnq8UJFhe/uYPZrYsnMzjg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3c481ed4-f247-44bb-a9d4-0d9ccf45a71e",
                            TwoFactorEnabled = false,
                            UserName = "User7"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750108",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "39373f11-7396-491a-af36-1f063997b527",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER8",
                            PasswordHash = "AQAAAAEAACcQAAAAEPY/Z+tC+i6+JHyv/JG/Jr++MuHadtq7VVnpkk0WO82MloVkAWG+xbUN0MPf24QGuA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "672207a2-5cfd-4951-8a69-f1bc8ccb405f",
                            TwoFactorEnabled = false,
                            UserName = "User8"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750109",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ee883a1e-a4bb-4164-bcfc-3a5c8ade57b9",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER9",
                            PasswordHash = "AQAAAAEAACcQAAAAEFbtRm1GayNmw5OlfNiG4RNSWLdDBoBt4xazLzMwEz7pYtqisYFot8E1FpPAza9LOQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3e93c0e9-2a23-40ce-99d3-2a83d4423949",
                            TwoFactorEnabled = false,
                            UserName = "User9"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750110",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "53eac1a6-fd88-4980-9dc2-492b49c241d5",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER10",
                            PasswordHash = "AQAAAAEAACcQAAAAEAlCa2ygZMcaMi8oal51ZB1wfJvfr33hHvElX0d9O54mYEKQ3D6/a8lZuykJ8M0lEg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "913ca758-e315-4a65-972a-56c50a96ac1e",
                            TwoFactorEnabled = false,
                            UserName = "User10"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1fe25d04-b638-43da-882b-06e486c829e1",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER11",
                            PasswordHash = "AQAAAAEAACcQAAAAEFxaSVoyT6NyKQsG+ObdlU+lggtj2dc23/WHbLHWrK9KuKkxl88gNPJQGA18OhFeQA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "30da87c5-45d0-4999-a1b6-5698178530e3",
                            TwoFactorEnabled = false,
                            UserName = "User11"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750112",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3d91760b-34a8-44ea-8a9f-7c288e5bcac0",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER12",
                            PasswordHash = "AQAAAAEAACcQAAAAEBwCoSZJ65uLofGeFkRbDuLvUWCB8JgA41ojgdgnu0Uo5liXHzGJh72NwKbPT5aE5w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9d8c3591-9a32-4200-bb69-648e3c670e92",
                            TwoFactorEnabled = false,
                            UserName = "User12"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750113",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a43843c9-27bb-4201-a228-be88966bbd10",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER13",
                            PasswordHash = "AQAAAAEAACcQAAAAEMbHfzfP9+wqcADQ0Up9EBn7wi7krUeKrFpOjkn48D54u7AbIOnnGPpnWBIJTGa/EQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b618b1a3-2af2-4d08-9745-5e1c11fe7b0d",
                            TwoFactorEnabled = false,
                            UserName = "User13"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750114",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "522fd93f-ce1c-437a-9c22-c709965931f2",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER14",
                            PasswordHash = "AQAAAAEAACcQAAAAEMHHVnGZQcT/628qm5PwGtjGHpU9/VVagbY6ii0dKbBX9W67o7532T7AgCGlOwu3Vw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d84ea3f8-4d34-4fd6-a6f6-7c656b756520",
                            TwoFactorEnabled = false,
                            UserName = "User14"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750115",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3361ca60-97ca-4b0f-9af7-465c0f5a4a19",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER15",
                            PasswordHash = "AQAAAAEAACcQAAAAEOUgwclb4qgHzTBGUZqhqgWwMZf5jodvDPZw0XrlCv2UWLYbzfX+BGe1Tt1Zt2VYqg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b99e7ba1-f8f2-4c70-afca-2758a81b2be2",
                            TwoFactorEnabled = false,
                            UserName = "User15"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750116",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b663effd-4513-4793-b5c7-d7150bd4ea87",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER16",
                            PasswordHash = "AQAAAAEAACcQAAAAEA2lqVYa5YYpvag41/N2KPmEqHrKGuFqRlZJkTuQC0OJP6p946JrSG0ZDvZuk7RpBA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b5dc8d1f-20f0-40fc-b7cb-1baf5849cb2f",
                            TwoFactorEnabled = false,
                            UserName = "User16"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750117",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0de1929f-b4fa-46c5-add8-c1280e3b594c",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER17",
                            PasswordHash = "AQAAAAEAACcQAAAAEPRPNrLu7lCS6xAS1whHpNkVcjFfLELDNMc65jk1KbMWkEsWcfo2vqlB39uVviTGdA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "577313c4-f1aa-477f-913a-245b3eeea97b",
                            TwoFactorEnabled = false,
                            UserName = "User17"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750118",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8f897587-e76c-4a70-a2cb-305fef1e7222",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER18",
                            PasswordHash = "AQAAAAEAACcQAAAAEBlUi0mdx7CeFbPdS5vOgzBwVomnpHfNuqf0vvegqUFXRSKcSWTVQx6i0D/P34FiIQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d921be7f-114a-4b60-9e76-2883e5536294",
                            TwoFactorEnabled = false,
                            UserName = "User18"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750119",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5e4493d6-620a-4f26-bcbc-5929fd270e43",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER19",
                            PasswordHash = "AQAAAAEAACcQAAAAENqU0o73Vol+hIVQujRBpG9jhao9ddZwvzphK+z6I+OxOSFrLd3AwZrpFbOJAcTD1g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8a691dc8-c39a-4f99-b244-ee03369206da",
                            TwoFactorEnabled = false,
                            UserName = "User19"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750120",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "35593337-a543-4696-846a-b6892a2bec6c",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER20",
                            PasswordHash = "AQAAAAEAACcQAAAAEI8/pdCpSUpx3pCXU3KxiNQUXr64f9Vb2Ngiq5ftqekdBxMoUpqAkhj48yPe103Faw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4f1e3968-28ec-4f5c-8454-ebdd74b4c1b4",
                            TwoFactorEnabled = false,
                            UserName = "User20"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750121",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "03aa2eba-f45b-4986-902f-bdce2928235a",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER21",
                            PasswordHash = "AQAAAAEAACcQAAAAEOKphDACUW5qqnpLYmYO1HrJ3vZFepVb4GH14yVTgyg4htpi4dbpss5lkM5lIqamjw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bcecbfe3-81b4-4e88-b63f-8f85b5f1ff89",
                            TwoFactorEnabled = false,
                            UserName = "User21"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750122",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e002f0c8-6164-42ed-8d04-3af4be897d03",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER22",
                            PasswordHash = "AQAAAAEAACcQAAAAEA2nc66J3DPetXkusI7IDZJPVRpr/MZw4QxebDTS+5NjpJrH8e9RRGDUiRhNvnWhpQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "40741fe9-6b28-48cd-aa94-39718eee6677",
                            TwoFactorEnabled = false,
                            UserName = "User22"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750123",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "71058a8a-4b8a-4b1a-9cdd-6a0a57e9fd91",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER23",
                            PasswordHash = "AQAAAAEAACcQAAAAECK8XGvDJdsGK9bR+tZdn4A3gdR9reyOf5lj7j4Dk/Y9Z/lavGYT1Iz3oYTAqhguxQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ce173c2e-adda-4ed7-942e-c5d08f428fab",
                            TwoFactorEnabled = false,
                            UserName = "User23"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750124",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5a63fde9-4767-4168-950b-ea1ebf6ea0f4",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER24",
                            PasswordHash = "AQAAAAEAACcQAAAAEJNqNNByqJh7MtvEX8ksD1cCSFde1E0rS9RZWPDLzoaFes4yj5GFQOfhWa1tsj6/MQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6d0bef11-ca13-445b-9813-396de3981ab4",
                            TwoFactorEnabled = false,
                            UserName = "User24"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750125",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9a87d0f5-6e3a-478c-93b3-3d42395619bc",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER25",
                            PasswordHash = "AQAAAAEAACcQAAAAEBca7yRKC3grP6YegKkWgQ74RnepFVnDfXq5rZ4d5sxI1YxYQNct09decYdC9Uf5Dg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f03aa8da-c9b8-4f5d-8293-d7a831f1fe14",
                            TwoFactorEnabled = false,
                            UserName = "User25"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750126",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f10646cf-df0a-4cb0-812c-a09310aff518",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER26",
                            PasswordHash = "AQAAAAEAACcQAAAAEKA+2XTozLtEnDZp1/fva7KZ7qqg+kHj9JuP2hX89jRlDgCwokz9hKRZ+2F7Nh/PAA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4ef50547-4616-4fea-9458-850832f198ef",
                            TwoFactorEnabled = false,
                            UserName = "User26"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750127",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aaff4803-0e78-4076-82c0-7cab81b88291",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER27",
                            PasswordHash = "AQAAAAEAACcQAAAAEHMMLC0+2w3ciXMrflKTMYMolcHqx843eNZLn5gWEGgy5GhoJ2YNXSK51lMxDcBhnw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "03fcf0eb-8898-4db9-a73d-7cf96136c675",
                            TwoFactorEnabled = false,
                            UserName = "User27"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750128",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9f0f31e0-4cef-4fdb-9dfd-73b55de4e11f",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER28",
                            PasswordHash = "AQAAAAEAACcQAAAAEAeD450g4ZFUV1U2QgwaTC+32CIcYjRRIVmD4EEUGmLufVR2/qAwHAlydCIR/2J1cQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8edf1702-e65a-4dae-94ad-66463fff0425",
                            TwoFactorEnabled = false,
                            UserName = "User28"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750129",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fa60d808-4fd6-4fd4-a926-79c6c73cc461",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER29",
                            PasswordHash = "AQAAAAEAACcQAAAAECzmRDrAET4q5Uh4G1uEKpJ699ZAqlfO9NJ8J+QMOGUntnAjbNS805Wo8BRKjgnDlw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "43786612-5da4-4c4c-9e29-f8b8702707d9",
                            TwoFactorEnabled = false,
                            UserName = "User29"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750130",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c9156ee8-28f4-414b-b91c-63090bb47fff",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER30",
                            PasswordHash = "AQAAAAEAACcQAAAAEFFeNlOhleIZvJ5Gvt+/SA589QICEvS5o/JsVzcHLTkkFqWYGJ5iEfZLBIeG1l+aQg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ebb2608c-8d30-441f-b995-9a3e9198c2be",
                            TwoFactorEnabled = false,
                            UserName = "User30"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750131",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "049f753b-71a0-431a-95c0-8f29269abd03",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER31",
                            PasswordHash = "AQAAAAEAACcQAAAAEEQunnf0G57MUQc0yC3Da8psdBZQRxCQ0C/7LQPL/8NIrAhlGYfmXoVDNPhwGd2OtA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "854c7fcc-8907-4e02-bd15-f6e43b89a1ad",
                            TwoFactorEnabled = false,
                            UserName = "User31"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750132",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1498094d-6e3a-4b95-8604-35c9f7952543",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER32",
                            PasswordHash = "AQAAAAEAACcQAAAAEHzIN2+3KF/JCPHjgO4ANT2WdfAdW8hiPiqy9REP8t9Lolo6a8xRYdY9VBiKcOhnSg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a8a99801-81a5-4e19-94c8-bdf0697baf81",
                            TwoFactorEnabled = false,
                            UserName = "User32"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750133",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1af35845-50de-40e7-8de7-0bc1f1a7b5fb",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER33",
                            PasswordHash = "AQAAAAEAACcQAAAAEHZHQReXSwakuvjeXfdt4S6lt2X/bx4phBBDTxbPO+/9ja7sfrgVqLu4WN9XsYeUAw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "11778c0d-b4de-4f01-bb28-887aa1026747",
                            TwoFactorEnabled = false,
                            UserName = "User33"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750134",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9067953e-524a-4d3d-9517-fec8f75e3e5f",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER34",
                            PasswordHash = "AQAAAAEAACcQAAAAEB6JVPcJzOgmsABGhIm+0dCdXMbmzjox6oypQwD8tvRSTDFRYK47HvwufCGMguhDVg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b442651a-c7e1-4d8d-890e-55af26d96a0e",
                            TwoFactorEnabled = false,
                            UserName = "User34"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750135",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "33ba4c7d-29aa-4260-93d1-2836651d7420",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER35",
                            PasswordHash = "AQAAAAEAACcQAAAAEBMSw2bRl5fzCysHh0r3yaWEbzdXSqFP4m1c3OlCCK34CwYg4E81BGLK42anXhapjA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "44f7f252-7d48-45d4-b187-561e21aa6103",
                            TwoFactorEnabled = false,
                            UserName = "User35"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750136",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dd2ab228-5205-4db6-89ab-06aefb0224cb",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER36",
                            PasswordHash = "AQAAAAEAACcQAAAAEKCY2MVGdutMJ6bt0W9o7JGeqOlAH1H9P5yJ99UsMdHQ7EHcI8FktT2ghmlcRBOWuA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "96c43098-6df8-4fdb-a66e-60afbd026fb1",
                            TwoFactorEnabled = false,
                            UserName = "User36"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750137",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b8f34b06-eb92-4516-873c-47885d42fade",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER37",
                            PasswordHash = "AQAAAAEAACcQAAAAEOfeH7z0wmZO7ZsHZHAdx9t12j3++Ed7Z+P78RIjzC3YmlEJBaQzEOt7Ijy0xeSUtg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3fabe98b-d417-49fe-be6e-53ee4e54fd9e",
                            TwoFactorEnabled = false,
                            UserName = "User37"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750138",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e45fbd09-7b83-4fbf-a7b1-705c4465f59f",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER38",
                            PasswordHash = "AQAAAAEAACcQAAAAEMTO1iPOwEQ3UOqc0uEuZATnHgsj45xzO2aZCDvAJAZrU0DLJ3W2+QKYCedscGsOJQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b53a7f02-8203-41e4-bfcc-7db0770469d4",
                            TwoFactorEnabled = false,
                            UserName = "User38"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750139",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1e874145-5e5e-43cc-b73c-e985aff30f38",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER39",
                            PasswordHash = "AQAAAAEAACcQAAAAEHdpBDzKgFGAVPUgGQ7qiYrhIwRw8+xxCvKOAEuUb5428s7FiNcxUnGA/c7i1roPRQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5ca3c8ec-d796-4b61-b4d9-c7f456877570",
                            TwoFactorEnabled = false,
                            UserName = "User39"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750140",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1f373008-a2f3-4b08-bb89-ceba7789f874",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER40",
                            PasswordHash = "AQAAAAEAACcQAAAAEPADTw7JYpD2NnCDEeV7TMKZBq1HbfpZg/rHDELRIoR19jrLruUdSIn9k/bVY1Pl4Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d15649d1-fb1c-4bc0-b07e-49deec62eeab",
                            TwoFactorEnabled = false,
                            UserName = "User40"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750141",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0c17995c-d0dc-4c47-b52d-0a76b1c42ab5",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER41",
                            PasswordHash = "AQAAAAEAACcQAAAAEFSAWMxRP5wjRUXU1rA7xbb0UZhe1+g3OdEyPxmYAXqG25EoOJtpSqKbcywgXeUwlA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7444c9f1-e377-4c33-8a2f-d796c7141b4e",
                            TwoFactorEnabled = false,
                            UserName = "User41"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750142",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4524ad59-f345-42a3-a3de-664248e0b402",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER42",
                            PasswordHash = "AQAAAAEAACcQAAAAENike4JHnn4bVm4J8yCR35V1k8hCTnGAbu4n9WLlbmPLZwJTy7rn4XUhCC3+HfW4QA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "32954478-3b1f-4197-90b0-b3cb8c04fcea",
                            TwoFactorEnabled = false,
                            UserName = "User42"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750143",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "04d36fad-0338-4c86-a14c-eec524c516a6",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER43",
                            PasswordHash = "AQAAAAEAACcQAAAAEEbAl1fDSlY9XNVf4EYwUXDM+RpEhWk7TyqiV9LkxEmWpuqwBnY/UUSrJUi9W4ZWnA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "def61888-5f68-4931-8a45-938dba408ffa",
                            TwoFactorEnabled = false,
                            UserName = "User43"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750144",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a5eae11e-4022-4c84-a5fe-cd782b0b9788",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER44",
                            PasswordHash = "AQAAAAEAACcQAAAAEIbQkF4bJzEiL0Q5RSEBlXTshquxHx67w0fk91VyN7qMq2Z9eeDPXnquAbLoTBNh1g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "53f1b8ca-2c24-40e7-a844-f4abef71d081",
                            TwoFactorEnabled = false,
                            UserName = "User44"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750145",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7512574a-f29b-47de-80b2-26ae9d54f3b6",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER45",
                            PasswordHash = "AQAAAAEAACcQAAAAEL6BtDoMiw4DmKJN4u0Nym4n2r9L54f0N+1QQVGQuNEEgr1DmSVIREQfjvZCmJvjjA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4ce49785-df2e-490e-8729-ab64e1a15c86",
                            TwoFactorEnabled = false,
                            UserName = "User45"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750146",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1815526c-9140-4de4-b17a-766856017d9a",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER46",
                            PasswordHash = "AQAAAAEAACcQAAAAEMMR8dcY3EJzIkjNTSK6CZnHJCri6ZKcQWAPrlFfw37No9pVo7wlpjzR5L+V6ty3Jg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "01ff8ec7-9add-4a1c-b4b6-5dfb7497eb55",
                            TwoFactorEnabled = false,
                            UserName = "User46"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750147",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1cf18a2b-90aa-4fd6-a478-f5f98c0d070f",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER47",
                            PasswordHash = "AQAAAAEAACcQAAAAEJglCsqv7TbzNN0xRnTfrmXDYSMg8i8ZDjdpgeNTspsOV1OIA0EnpYqXxhMC18J73w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a269a279-e8ed-4aed-898c-92fb0b63a1d2",
                            TwoFactorEnabled = false,
                            UserName = "User47"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750148",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "af5c625f-ded5-434c-a21d-37c108ad7cd7",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER48",
                            PasswordHash = "AQAAAAEAACcQAAAAEFHUo22y9qKnDDwiYgGMEf6GmcXU/M3XlwJ5dFdfSuxz3FDGZxdtYzO6l9wyCK0Q3g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "24a304a1-c781-4e35-9a86-777fd50b965f",
                            TwoFactorEnabled = false,
                            UserName = "User48"
                        },
                        new
                        {
                            Id = "4c33537b-e856-463b-811e-e8e059750149",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "12d6f2ba-f6a8-421b-b823-78f527258d6f",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER49",
                            PasswordHash = "AQAAAAEAACcQAAAAEIVeeZ0QvmvgjHsIRQibyDd0erpt8N/SqzQ9J2u4t5Ib7UmTKD4nZ8ct49CBDwb36w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "813c6108-8a70-45d9-a080-ecb33ed3d141",
                            TwoFactorEnabled = false,
                            UserName = "User49"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
